"""Phase 5.4 -- apply the decision rule mechanically, before any figure is polished.

The rule is written down in the plan so that it cannot drift once the numbers are in.
This module encodes it literally and emits its verdict to results/verdict.md; reading
the figures first and then deciding what counts as support is how a preliminary result
becomes an unreproducible one.
"""

from __future__ import annotations

import json

import pandas as pd

from .. import paths
from ..config import load


def _pick(comparisons: pd.DataFrame, dataset: str, model: str,
          arm_a: str, arm_b: str, metric: str) -> pd.Series | None:
    hit = comparisons[
        (comparisons["dataset"] == dataset) & (comparisons["model"] == model)
        & (comparisons["arm_a"] == arm_a) & (comparisons["arm_b"] == arm_b)
        & (comparisons["metric"] == metric)
    ]
    return None if hit.empty else hit.iloc[0]


def evaluate_cell(comparisons: pd.DataFrame, dataset: str, model: str, cfg) -> dict:
    drop_target = float(cfg.eval.ambiguity_rel_drop)
    margin = float(cfg.eval.auroc_margin)

    amb = _pick(comparisons, dataset, model, "distilled", "hard", "ambiguity")
    auc = _pick(comparisons, dataset, model, "distilled", "hard", "mean_auroc")

    if amb is None or auc is None:
        return {"dataset": dataset, "model": model, "verdict": "missing",
                "reason": "distilled-vs-hard comparison not available"}

    rel_drop = -float(amb["relative_change"])          # negative delta == a drop
    ci_excludes_zero = float(amb["delta_ci_high"]) < 0.0
    auroc_ok = float(auc["delta_ci_low"]) >= margin

    if rel_drop >= drop_target and ci_excludes_zero and auroc_ok:
        verdict, reason = "supports", "ambiguity drop met and AUROC non-inferior"
    elif rel_drop < 0.10 or not auroc_ok:
        verdict = "refutes"
        reasons = []
        if rel_drop < 0.10:
            reasons.append(f"ambiguity drop {rel_drop:.1%} below the 10% floor")
        if not auroc_ok:
            reasons.append(f"AUROC CI low {float(auc['delta_ci_low']):+.4f} below margin {margin}")
        reason = "; ".join(reasons)
    else:
        verdict, reason = "inconclusive", "effect present but below the support threshold"

    return {
        "dataset": dataset, "model": model, "verdict": verdict, "reason": reason,
        "ambiguity_relative_drop": rel_drop,
        "ambiguity_delta": float(amb["delta_point"]),
        "ambiguity_ci": [float(amb["delta_ci_low"]), float(amb["delta_ci_high"])],
        "auroc_delta": float(auc["delta_point"]),
        "auroc_ci": [float(auc["delta_ci_low"]), float(auc["delta_ci_high"])],
    }


def write_verdict(datasets: list[str], models: list[str]) -> dict:
    comparisons = pd.read_csv(paths.RESULTS / "comparisons.csv")
    cells = []
    for dataset in datasets:
        cfg = load(dataset)
        for model in models:
            cells.append(evaluate_cell(comparisons, dataset, model, cfg))

    verdicts = {c["verdict"] for c in cells}
    if verdicts == {"supports"}:
        overall = "H2 supported on both datasets and both model families"
    elif "refutes" in verdicts and "supports" not in verdicts:
        overall = "H2 refuted"
    elif "supports" in verdicts:
        overall = "H2 supported only in some cells -- report as dataset/model dependent, do not claim H2"
    else:
        overall = "Inconclusive"

    lines = ["# Verdict", "", f"**Overall:** {overall}", "",
             "| Dataset | Model | Verdict | Ambiguity drop | ΔAUROC [95% CI] | Reason |",
             "|---|---|---|---|---|---|"]
    for c in cells:
        if c["verdict"] == "missing":
            lines.append(f"| {c['dataset']} | {c['model']} | missing | — | — | {c['reason']} |")
            continue
        lo, hi = c["auroc_ci"]
        lines.append(
            f"| {c['dataset']} | {c['model']} | **{c['verdict']}** | "
            f"{c['ambiguity_relative_drop']:.1%} | {c['auroc_delta']:+.4f} [{lo:+.4f}, {hi:+.4f}] | "
            f"{c['reason']} |"
        )
    lines += ["", "Generated by `tfmdm verdict`; the rule it applies is fixed in the plan and in "
              "`configs/base.yaml` (`eval.ambiguity_rel_drop`, `eval.auroc_margin`).", "",
              "**Limitation.** With no smoothing control in the design, a drop here cannot be "
              "attributed to TabICLv2 specifically rather than to soft targets in general "
              "(decision D4)."]

    (paths.RESULTS / "verdict.md").write_text("\n".join(lines) + "\n")
    payload = {"overall": overall, "cells": cells}
    (paths.RESULTS / "verdict.json").write_text(json.dumps(payload, indent=2, default=float))
    return payload
